-- Stage 2C: 日/月/抄表模块
-- 热表日记录、月记录、抄表记录三张表

-- ========================================
-- 1. 热表日记录表
-- ========================================
DROP TABLE IF EXISTS `pr_heat_daily`;
CREATE TABLE `pr_heat_daily` (
    `id` varchar(36) NOT NULL COMMENT '主键',
    `tenant_id` varchar(20) DEFAULT '000000' COMMENT '租户编号',
    `meter_id` varchar(36) DEFAULT NULL COMMENT '配表ID',
    `meter_num` varchar(36) DEFAULT NULL COMMENT '表号',
    `card_num` varchar(36) DEFAULT NULL COMMENT '卡号',
    `meter_arc_code` varchar(36) DEFAULT NULL COMMENT '热表档案编号',
    `start_time` datetime DEFAULT NULL COMMENT '上次抄表时间',
    `start_reading` decimal(12,2) DEFAULT 0.00 COMMENT '上次读数',
    `read_time` datetime DEFAULT NULL COMMENT '本次抄表时间',
    `current_reading` decimal(12,2) DEFAULT 0.00 COMMENT '当前读数',
    `qty` decimal(12,2) DEFAULT 0.00 COMMENT '日用量',
    `in_temperature` decimal(8,2) DEFAULT 0.00 COMMENT '进水温度',
    `out_temperature` decimal(8,2) DEFAULT 0.00 COMMENT '回水温度',
    `diff_temperature` decimal(8,2) DEFAULT 0.00 COMMENT '供回水温差',
    `setting_status` varchar(20) DEFAULT NULL COMMENT '阀门设定状态',
    `valve_status` varchar(20) DEFAULT NULL COMMENT '阀门当前状态',
    `voltage` varchar(20) DEFAULT NULL COMMENT '电压',
    `standard_price` decimal(12,6) DEFAULT 0.000000 COMMENT '基本单价',
    `total_money` decimal(12,2) DEFAULT 0.00 COMMENT '总金额',
    `daily_date` datetime DEFAULT NULL COMMENT '日表所属日期',
    `is_calc` int DEFAULT NULL COMMENT '是否计算用量',
    `calc_date` datetime DEFAULT NULL COMMENT '费用结算时间',
    `house_id` varchar(36) DEFAULT NULL COMMENT '房屋ID',
    `org_id` varchar(36) DEFAULT NULL COMMENT '小区ID',
    `company_id` varchar(36) DEFAULT NULL COMMENT '公司ID',
    `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
    `create_by` bigint DEFAULT NULL COMMENT '创建者',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint DEFAULT NULL COMMENT '修改者',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    PRIMARY KEY (`id`),
    KEY `idx_company_org` (`company_id`, `org_id`),
    KEY `idx_house_id` (`house_id`),
    KEY `idx_meter_num` (`meter_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='热表日记录表';

-- ========================================
-- 2. 热表月记录表
-- ========================================
DROP TABLE IF EXISTS `pr_heat_month`;
CREATE TABLE `pr_heat_month` (
    `id` varchar(36) NOT NULL COMMENT '主键',
    `tenant_id` varchar(20) DEFAULT '000000' COMMENT '租户编号',
    `meter_num` varchar(36) DEFAULT NULL COMMENT '表号',
    `card_num` varchar(36) DEFAULT NULL COMMENT '卡号',
    `meter_id` varchar(36) DEFAULT NULL COMMENT '配表ID',
    `meter_arc_code` varchar(36) DEFAULT NULL COMMENT '热表档案编号',
    `start_time` datetime DEFAULT NULL COMMENT '上次抄表时间',
    `read_time` datetime DEFAULT NULL COMMENT '本次抄表时间',
    `start_reading` decimal(12,2) DEFAULT 0.00 COMMENT '上次读数',
    `current_reading` decimal(12,2) DEFAULT 0.00 COMMENT '本次读数',
    `qty` decimal(12,2) DEFAULT 0.00 COMMENT '当月用量',
    `record_ym` varchar(10) DEFAULT NULL COMMENT '结算月份/年份(如202008)',
    `statistics_type` varchar(20) DEFAULT NULL COMMENT '统计方式',
    `standard_id` varchar(36) DEFAULT NULL COMMENT '收费标准ID',
    `total_money` decimal(12,2) DEFAULT 0.00 COMMENT '总金额',
    `is_audit` int DEFAULT NULL COMMENT '是否审批',
    `is_hiscalc` int DEFAULT NULL COMMENT '是否参与历史累计',
    `current_balance` decimal(12,2) DEFAULT 0.00 COMMENT '当前余额',
    `recharge_money` decimal(12,2) DEFAULT 0.00 COMMENT '当月充值金额',
    `pay_degrees` decimal(12,2) DEFAULT 0.00 COMMENT '缴至读数',
    `current_arrearage` decimal(12,2) DEFAULT 0.00 COMMENT '本月欠费',
    `add_arrearage` decimal(12,2) DEFAULT 0.00 COMMENT '累计欠费',
    `add_advances` decimal(12,2) DEFAULT 0.00 COMMENT '累计预收',
    `house_id` varchar(36) DEFAULT NULL COMMENT '房屋ID',
    `org_id` varchar(36) DEFAULT NULL COMMENT '小区ID',
    `company_id` varchar(36) DEFAULT NULL COMMENT '公司ID',
    `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
    `create_by` bigint DEFAULT NULL COMMENT '创建者',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint DEFAULT NULL COMMENT '修改者',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    PRIMARY KEY (`id`),
    KEY `idx_company_org` (`company_id`, `org_id`),
    KEY `idx_house_id` (`house_id`),
    KEY `idx_meter_num` (`meter_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='热表月记录表';

-- ========================================
-- 3. 热表抄表记录表
-- ========================================
DROP TABLE IF EXISTS `pr_heat_reading`;
CREATE TABLE `pr_heat_reading` (
    `id` varchar(36) NOT NULL COMMENT '主键',
    `tenant_id` varchar(20) DEFAULT '000000' COMMENT '租户编号',
    `manu_id` varchar(36) DEFAULT NULL COMMENT '厂家反馈的产品代码',
    `meter_arc_code` varchar(36) DEFAULT NULL COMMENT '热表档案编号',
    `meter_num` varchar(36) DEFAULT NULL COMMENT '表号',
    `card_num` varchar(36) DEFAULT NULL COMMENT '卡号',
    `device_id` varchar(36) DEFAULT NULL COMMENT '平台给终端分配的设备ID',
    `in_temperature` decimal(8,2) DEFAULT 0.00 COMMENT '进水温度',
    `out_temperature` decimal(8,2) DEFAULT 0.00 COMMENT '回水温度',
    `diff_temperature` decimal(8,2) DEFAULT 0.00 COMMENT '供回水温差',
    `total_heat` decimal(12,2) DEFAULT 0.00 COMMENT '累积热量',
    `total_flow` decimal(12,2) DEFAULT 0.00 COMMENT '累积流量',
    `flow_rate` decimal(12,2) DEFAULT 0.00 COMMENT '瞬时流量',
    `total_worktime` decimal(12,2) DEFAULT 0.00 COMMENT '累积工作时间',
    `water_press` decimal(8,2) DEFAULT 0.00 COMMENT '水压',
    `reverse_flow` decimal(12,2) DEFAULT 0.00 COMMENT '反向流量',
    `setting_status` varchar(20) DEFAULT NULL COMMENT '阀门设定状态',
    `valve_status` varchar(20) DEFAULT NULL COMMENT '阀门当前状态',
    `power_state` varchar(20) DEFAULT NULL COMMENT '电源状态',
    `attack_status` varchar(20) DEFAULT NULL COMMENT '异常状态',
    `read_time` datetime DEFAULT NULL COMMENT '抄表时间',
    `st` varchar(50) DEFAULT NULL COMMENT '状态字',
    `is_used` int DEFAULT NULL COMMENT '是否使用',
    `is_valid` int DEFAULT NULL COMMENT '是否有效(是否系统内表号)',
    `org_id` varchar(36) DEFAULT NULL COMMENT '小区ID',
    `company_id` varchar(36) DEFAULT NULL COMMENT '公司ID',
    `csq` varchar(20) DEFAULT NULL COMMENT '信号',
    `voltage` varchar(20) DEFAULT NULL COMMENT '电压',
    `humi` varchar(20) DEFAULT NULL COMMENT '湿度',
    `temperature` decimal(8,2) DEFAULT 0.00 COMMENT '温度',
    `heat_power` decimal(12,2) DEFAULT 0.00 COMMENT '热功率',
    `status1` varchar(50) DEFAULT NULL COMMENT '热表状态1',
    `status2` varchar(50) DEFAULT NULL COMMENT '热表状态2',
    `meter_serial` int DEFAULT NULL COMMENT '子表序号',
    `user_set_temp` decimal(8,2) DEFAULT NULL COMMENT '用户设定温度',
    `room_temp` decimal(8,2) DEFAULT NULL COMMENT '室内温度',
    `avg_temp` decimal(8,2) DEFAULT NULL COMMENT '平均温度',
    `valve_model` varchar(50) DEFAULT NULL COMMENT '阀门型号',
    `cold_flg` int DEFAULT NULL COMMENT '冷水标志',
    `wkq_lock` int DEFAULT NULL COMMENT '温控器锁定',
    `temp_low` int DEFAULT NULL COMMENT '温度下限',
    `temp_high` int DEFAULT NULL COMMENT '温度上限',
    `work_time` int DEFAULT NULL COMMENT '工作时间',
    `total_open_time` int DEFAULT NULL COMMENT '总开启时间',
    `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
    `create_by` bigint DEFAULT NULL COMMENT '创建者',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint DEFAULT NULL COMMENT '修改者',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    PRIMARY KEY (`id`),
    KEY `idx_company_org` (`company_id`, `org_id`),
    KEY `idx_meter_num` (`meter_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='热表抄表记录表';
