-- Phase 6: 配表模块（9张配表）DDL
-- 迁移自旧系统配表模块
-- 数据库: ry-vue / 字符集: utf8mb4

-- ========================================
-- 1. pr_heat_archive (房屋热表配表)
-- 68 persisted columns
-- ========================================
DROP TABLE IF EXISTS `pr_heat_archive`;
CREATE TABLE `pr_heat_archive` (
    `id`                  varchar(36)  NOT NULL COMMENT '主键',
    `company_id`          varchar(32)  DEFAULT NULL COMMENT '公司ID',
    `org_id`              varchar(32)  DEFAULT NULL COMMENT '小区ID',
    `org_name`            varchar(128) DEFAULT NULL COMMENT '小区名称',
    `building_name`       varchar(128) DEFAULT NULL COMMENT '楼栋名称',
    `house_id`            varchar(32)  DEFAULT NULL COMMENT '房屋ID',
    `room_num`            varchar(32)  DEFAULT NULL COMMENT '房号',
    `archive_id`          varchar(32)  DEFAULT NULL COMMENT '配表ID(关联)',
    `meter_arc_code`      varchar(32)  DEFAULT NULL COMMENT '仪表档案编码',
    `meter_arc_name`      varchar(64)  DEFAULT NULL COMMENT '仪表档案名称',
    `meter_num`           varchar(32)  DEFAULT NULL COMMENT '表号',
    `imei`                varchar(50)  DEFAULT NULL COMMENT 'IMEI号',
    `card_num`            varchar(32)  DEFAULT NULL COMMENT '卡号',
    `product_id`          varchar(32)  DEFAULT NULL COMMENT '产品ID',
    `device_id`           varchar(32)  DEFAULT NULL COMMENT '设备ID',
    `meter_serial`        int          DEFAULT NULL COMMENT '仪表序号',
    `line_number`         varchar(32)  DEFAULT NULL COMMENT '线路号',
    `specification`       varchar(64)  DEFAULT NULL COMMENT '规格',
    `model`               varchar(64)  DEFAULT NULL COMMENT '型号',
    `concentrator_code`   varchar(32)  DEFAULT NULL COMMENT '集中器编码',
    `install_site`        varchar(128) DEFAULT NULL COMMENT '安装位置',
    `standard_id`         varchar(32)  DEFAULT NULL COMMENT '收费标准ID',
    `standard_price`      decimal(10,2) DEFAULT 0.00 COMMENT '标准单价',
    `in_temperature`      decimal(10,2) DEFAULT NULL COMMENT '进水温度',
    `out_temperature`     decimal(10,2) DEFAULT NULL COMMENT '回水温度',
    `diff_temperature`    decimal(10,2) DEFAULT NULL COMMENT '温差',
    `setting_temperature` decimal(10,2) DEFAULT 0.00 COMMENT '设定温度',
    `setting_status`      int          DEFAULT NULL COMMENT '设定状态',
    `valve_status`        varchar(10)  DEFAULT NULL COMMENT '阀门状态',
    `is_opened`           int          DEFAULT 0 COMMENT '是否开户 0否1是',
    `opened_time`         datetime     DEFAULT NULL COMMENT '开户时间',
    `his_money`           decimal(10,2) DEFAULT 0.00 COMMENT '历史金额',
    `total_used`          decimal(10,2) DEFAULT 0.00 COMMENT '累计用量',
    `current_reading`     decimal(10,2) DEFAULT 0.00 COMMENT '当前读数',
    `total_money`         decimal(10,2) DEFAULT 0.00 COMMENT '累计金额',
    `total_recharge`      decimal(10,2) DEFAULT 0.00 COMMENT '累计充值',
    `current_balance`     decimal(10,2) DEFAULT 0.00 COMMENT '当前余额',
    `pay_degrees`         decimal(10,2) DEFAULT 0.00 COMMENT '已购量',
    `start_reading`       int          DEFAULT NULL COMMENT '起始读数',
    `total_heat`          decimal(10,2) DEFAULT NULL COMMENT '累计热量',
    `total_flow`          decimal(10,2) DEFAULT NULL COMMENT '累计流量',
    `total_worktime`      decimal(10,2) DEFAULT NULL COMMENT '累计工作时间',
    `trade_times`         int          DEFAULT 0 COMMENT '购买倍数',
    `hoard_limit`         decimal(10,2) DEFAULT NULL COMMENT '囤积限值',
    `alarm_value`         decimal(10,2) DEFAULT NULL COMMENT '报警值',
    `close_value`         decimal(10,2) DEFAULT NULL COMMENT '关阀值',
    `is_steps`            int          DEFAULT 0 COMMENT '是否阶梯 0否1是',
    `measurement`         varchar(32)  DEFAULT NULL COMMENT '计量方式',
    `type`                varchar(32)  DEFAULT NULL COMMENT '类型',
    `command`             varchar(50)  DEFAULT NULL COMMENT '指令',
    `valve_opening`       varchar(10)  DEFAULT NULL COMMENT '阀门开度',
    `command_time`        datetime     DEFAULT NULL COMMENT '指令下发时间',
    `return_time`         datetime     DEFAULT NULL COMMENT '指令返回时间',
    `command_status`      varchar(50)  DEFAULT NULL COMMENT '指令状态',
    `is_expense`          int          DEFAULT 0 COMMENT '是否产生费用 0否1是',
    `is_notify`           int          DEFAULT 0 COMMENT '是否通知 0否1是',
    `is_changed`          int          DEFAULT 0 COMMENT '是否换表 0否1是',
    `is_stop`             int          DEFAULT 0 COMMENT '是否停用 0否1是',
    `del_flag`            char(1)      DEFAULT '0' COMMENT '删除标志(0存在 1删除)',
    `is_print`            varchar(10)  DEFAULT NULL COMMENT '是否打印',
    `print_type`          varchar(10)  DEFAULT NULL COMMENT '打印类型',
    `create_dept`         bigint       DEFAULT NULL COMMENT '创建部门',
    `create_by`           varchar(40)  DEFAULT NULL COMMENT '创建者',
    `create_time`         datetime     DEFAULT NULL COMMENT '创建时间',
    `update_by`           varchar(40)  DEFAULT NULL COMMENT '修改者',
    `update_time`         datetime     DEFAULT NULL COMMENT '修改时间',
    `remark`              varchar(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_company_id` (`company_id`),
    KEY `idx_org_id` (`org_id`),
    KEY `idx_house_id` (`house_id`),
    KEY `idx_meter_num` (`meter_num`),
    KEY `idx_archive_id` (`archive_id`),
    KEY `idx_company_org` (`company_id`, `org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='房屋热表配表';

-- ========================================
-- 2. pr_heat_valve_archive (户间阀门配表)
-- 59 persisted columns
-- ========================================
DROP TABLE IF EXISTS `pr_heat_valve_archive`;
CREATE TABLE `pr_heat_valve_archive` (
    `id`                      varchar(36)   NOT NULL COMMENT '主键',
    `archive_id`              varchar(32)   DEFAULT NULL COMMENT '配表ID(关联)',
    `meter_num`               varchar(32)   DEFAULT NULL COMMENT '表号',
    `card_num`                varchar(32)   DEFAULT NULL COMMENT '卡号',
    `meter_arc_code`          varchar(32)   DEFAULT NULL COMMENT '仪表档案编码',
    `meter_arc_name`          varchar(64)   DEFAULT NULL COMMENT '仪表档案名称',
    `concentrator_code`       varchar(32)   DEFAULT NULL COMMENT '集中器编码',
    `imei_num`                varchar(50)   DEFAULT NULL COMMENT 'IMEI号',
    `product_id`              varchar(32)   DEFAULT NULL COMMENT '产品ID',
    `device_id`               varchar(32)   DEFAULT NULL COMMENT '设备ID',
    `meter_serial`            int           DEFAULT NULL COMMENT '仪表序号',
    `house_id`                varchar(32)   DEFAULT NULL COMMENT '房屋ID',
    `org_id`                  varchar(32)   DEFAULT NULL COMMENT '小区ID',
    `company_id`              varchar(32)   DEFAULT NULL COMMENT '公司ID',
    `valve_status`            varchar(10)   DEFAULT NULL COMMENT '阀门状态',
    `setting_status`          int           DEFAULT NULL COMMENT '设定状态',
    `actual_status`           int           DEFAULT NULL COMMENT '实际状态',
    `in_temperature`          decimal(10,2) DEFAULT NULL COMMENT '进水温度',
    `out_temperature`         decimal(10,2) DEFAULT NULL COMMENT '回水温度',
    `voltage`                 varchar(20)   DEFAULT NULL COMMENT '电压',
    `valve_time`              datetime      DEFAULT NULL COMMENT '阀门时间',
    `signal_strength`         int           DEFAULT NULL COMMENT '信号强度',
    `reporting_interval`      int           DEFAULT NULL COMMENT '上报间隔',
    `total_degree`            int           DEFAULT NULL COMMENT '总度数',
    `residue_degree`          int           DEFAULT NULL COMMENT '剩余度数',
    `interval_unit`           varchar(20)   DEFAULT NULL COMMENT '间隔单位',
    `valid_time`              int           DEFAULT NULL COMMENT '有效时间',
    `is_changed`              int           DEFAULT 0 COMMENT '是否换表 0否1是',
    `is_stop`                 int           DEFAULT 0 COMMENT '是否停用 0否1是',
    `chan_num_update_time`    datetime      DEFAULT NULL COMMENT '通道号更新时间',
    `chan_num_sync_time`      datetime      DEFAULT NULL COMMENT '通道号同步时间',
    `last_perform_id`         varchar(50)   DEFAULT NULL COMMENT '最后执行ID',
    `dtu_num`                 varchar(50)   DEFAULT NULL COMMENT 'DTU号',
    `dtu_num_status`          varchar(20)   DEFAULT NULL COMMENT 'DTU号状态',
    `chan_num`                varchar(20)   DEFAULT NULL COMMENT '通道号',
    `install_site`            varchar(128)  DEFAULT NULL COMMENT '安装位置',
    `dtu_status`              varchar(20)   DEFAULT NULL COMMENT 'DTU状态',
    `trade_times`             int           DEFAULT NULL COMMENT '购买倍数',
    `is_open`                 int           DEFAULT 0 COMMENT '是否开户 0否1是',
    `caliber`                 varchar(20)   DEFAULT NULL COMMENT '口径',
    `install_type`            varchar(50)   DEFAULT NULL COMMENT '安装方式',
    `group_num25`             varchar(50)   DEFAULT NULL COMMENT '分组号25',
    `user_set_temp`           decimal(10,2) DEFAULT NULL COMMENT '用户设定温度',
    `room_temp`               decimal(10,2) DEFAULT NULL COMMENT '室温',
    `avg_temp`                decimal(10,2) DEFAULT NULL COMMENT '平均温度',
    `valve_model`             varchar(50)   DEFAULT NULL COMMENT '阀门型号',
    `cold_flg`                int           DEFAULT 0 COMMENT '冷阀标志 0否1是',
    `wkq_lock`                int           DEFAULT 0 COMMENT '温控器锁定 0否1是',
    `temp_low`                int           DEFAULT NULL COMMENT '温度下限',
    `temp_high`               int           DEFAULT NULL COMMENT '温度上限',
    `work_time`               int           DEFAULT NULL COMMENT '工作时间',
    `total_open_time`         int           DEFAULT NULL COMMENT '累计开启时间',
    `dtu_type`                int           DEFAULT NULL COMMENT 'DTU类型',
    `ins_flow`                decimal(10,2) DEFAULT NULL COMMENT '瞬时流量',
    `create_dept`             bigint        DEFAULT NULL COMMENT '创建部门',
    `create_by`               varchar(40)   DEFAULT NULL COMMENT '创建者',
    `create_time`             datetime      DEFAULT NULL COMMENT '创建时间',
    `update_by`               varchar(40)   DEFAULT NULL COMMENT '修改者',
    `update_time`             datetime      DEFAULT NULL COMMENT '修改时间',
    `remark`                  varchar(500)  DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_company_id` (`company_id`),
    KEY `idx_org_id` (`org_id`),
    KEY `idx_house_id` (`house_id`),
    KEY `idx_meter_num` (`meter_num`),
    KEY `idx_archive_id` (`archive_id`),
    KEY `idx_company_org` (`company_id`, `org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='户间阀门配表';

-- ========================================
-- 3. pr_heat_command_valve_archive (户间控制阀门配表)
-- 43 persisted columns
-- ========================================
DROP TABLE IF EXISTS `pr_heat_command_valve_archive`;
CREATE TABLE `pr_heat_command_valve_archive` (
    `id`                  varchar(36)   NOT NULL COMMENT '主键',
    `archive_id`          varchar(32)   DEFAULT NULL COMMENT '配表ID(关联)',
    `meter_num`           varchar(32)   DEFAULT NULL COMMENT '表号',
    `card_num`            varchar(32)   DEFAULT NULL COMMENT '卡号',
    `meter_arc_code`      varchar(32)   DEFAULT NULL COMMENT '仪表档案编码',
    `meter_arc_name`      varchar(64)   DEFAULT NULL COMMENT '仪表档案名称',
    `concentrator_code`   varchar(32)   DEFAULT NULL COMMENT '集中器编码',
    `imei_num`            varchar(50)   DEFAULT NULL COMMENT 'IMEI号',
    `product_id`          varchar(32)   DEFAULT NULL COMMENT '产品ID',
    `device_id`           varchar(32)   DEFAULT NULL COMMENT '设备ID',
    `meter_serial`        int           DEFAULT NULL COMMENT '仪表序号',
    `house_id`            varchar(32)   DEFAULT NULL COMMENT '房屋ID',
    `org_id`              varchar(32)   DEFAULT NULL COMMENT '小区ID',
    `company_id`          varchar(32)   DEFAULT NULL COMMENT '公司ID',
    `valve_status`        varchar(10)   DEFAULT NULL COMMENT '阀门状态',
    `setting_status`      int           DEFAULT NULL COMMENT '设定状态',
    `actual_status`       int           DEFAULT NULL COMMENT '实际状态',
    `in_temperature`      decimal(10,2) DEFAULT NULL COMMENT '进水温度',
    `out_temperature`     decimal(10,2) DEFAULT NULL COMMENT '回水温度',
    `voltage`             varchar(20)   DEFAULT NULL COMMENT '电压',
    `valve_time`          datetime      DEFAULT NULL COMMENT '阀门时间',
    `signal_strength`     int           DEFAULT NULL COMMENT '信号强度',
    `reporting_interval`  int           DEFAULT NULL COMMENT '上报间隔',
    `total_degree`        int           DEFAULT NULL COMMENT '总度数',
    `residue_degree`      int           DEFAULT NULL COMMENT '剩余度数',
    `interval_unit`       varchar(20)   DEFAULT NULL COMMENT '间隔单位',
    `valid_time`          int           DEFAULT NULL COMMENT '有效时间',
    `is_changed`          int           DEFAULT 0 COMMENT '是否换表 0否1是',
    `is_stop`             int           DEFAULT 0 COMMENT '是否停用 0否1是',
    `dtu_num`             varchar(50)   DEFAULT NULL COMMENT 'DTU号',
    `dtu_type`            int           DEFAULT NULL COMMENT 'DTU类型',
    `dtu_num_status`      varchar(20)   DEFAULT NULL COMMENT 'DTU号状态',
    `chan_num`            varchar(20)   DEFAULT NULL COMMENT '通道号',
    `install_site`        varchar(128)  DEFAULT NULL COMMENT '安装位置',
    `dtu_status`          varchar(20)   DEFAULT NULL COMMENT 'DTU状态',
    `trade_times`         int           DEFAULT 0 COMMENT '购买倍数',
    `is_open`             int           DEFAULT 0 COMMENT '是否开户 0否1是',
    `caliber`             varchar(20)   DEFAULT NULL COMMENT '口径',
    `create_dept`         bigint        DEFAULT NULL COMMENT '创建部门',
    `create_by`           varchar(40)   DEFAULT NULL COMMENT '创建者',
    `create_time`         datetime      DEFAULT NULL COMMENT '创建时间',
    `update_by`           varchar(40)   DEFAULT NULL COMMENT '修改者',
    `update_time`         datetime      DEFAULT NULL COMMENT '修改时间',
    `remark`              varchar(500)  DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_company_id` (`company_id`),
    KEY `idx_org_id` (`org_id`),
    KEY `idx_house_id` (`house_id`),
    KEY `idx_meter_num` (`meter_num`),
    KEY `idx_archive_id` (`archive_id`),
    KEY `idx_company_org` (`company_id`, `org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='户间控制阀门配表';

-- ========================================
-- 4. pr_heat_hot_archive (房屋热量表配表)
-- 61 persisted columns
-- ========================================
DROP TABLE IF EXISTS `pr_heat_hot_archive`;
CREATE TABLE `pr_heat_hot_archive` (
    `id`                  varchar(36)   NOT NULL COMMENT '主键',
    `archive_id`          varchar(32)   DEFAULT NULL COMMENT '配表ID(关联)',
    `meter_arc_code`      varchar(32)   DEFAULT NULL COMMENT '仪表档案编码',
    `meter_arc_name`      varchar(64)   DEFAULT NULL COMMENT '仪表档案名称',
    `meter_num`           varchar(32)   DEFAULT NULL COMMENT '表号',
    `card_num`            varchar(32)   DEFAULT NULL COMMENT '卡号',
    `product_id`          varchar(32)   DEFAULT NULL COMMENT '产品ID',
    `device_id`           varchar(32)   DEFAULT NULL COMMENT '设备ID',
    `meter_serial`        int           DEFAULT NULL COMMENT '仪表序号',
    `concentrator_code`   varchar(32)   DEFAULT NULL COMMENT '集中器编码',
    `hoard_limit`         decimal(10,2) DEFAULT NULL COMMENT '囤积限值',
    `alarm_value`         decimal(10,2) DEFAULT NULL COMMENT '报警值',
    `close_value`         bigint        DEFAULT NULL COMMENT '关阀值',
    `measurement`         varchar(32)   DEFAULT NULL COMMENT '计量方式',
    `install_site`        varchar(128)  DEFAULT NULL COMMENT '安装位置',
    `standard_id`         varchar(32)   DEFAULT NULL COMMENT '收费标准ID',
    `standard_price`      decimal(10,2) DEFAULT 0.00 COMMENT '标准单价',
    `is_steps`            int           DEFAULT 0 COMMENT '是否阶梯 0否1是',
    `start_reading`       decimal(10,2) DEFAULT NULL COMMENT '起始读数',
    `current_reading`     decimal(10,2) DEFAULT 0.00 COMMENT '当前读数',
    `total_used`          decimal(10,2) DEFAULT 0.00 COMMENT '累计用量',
    `trade_times`         int           DEFAULT 0 COMMENT '购买倍数',
    `his_money`           decimal(10,2) DEFAULT 0.00 COMMENT '历史金额',
    `total_money`         decimal(10,2) DEFAULT 0.00 COMMENT '累计金额',
    `total_recharge`      decimal(10,2) DEFAULT 0.00 COMMENT '累计充值',
    `current_balance`     decimal(10,2) DEFAULT 0.00 COMMENT '当前余额',
    `pay_degrees`         decimal(10,2) DEFAULT 0.00 COMMENT '已购量',
    `valve_status`        varchar(10)   DEFAULT NULL COMMENT '阀门状态',
    `total_flow`          decimal(10,2) DEFAULT 0.00 COMMENT '累计流量',
    `cur_flow`            decimal(10,2) DEFAULT 0.00 COMMENT '当前流量',
    `total_worktime`      decimal(10,2) DEFAULT 0.00 COMMENT '累计工作时间',
    `valve_time`          datetime      DEFAULT NULL COMMENT '阀门时间',
    `status1`             varchar(50)   DEFAULT NULL COMMENT '状态1',
    `status2`             varchar(50)   DEFAULT NULL COMMENT '状态2',
    `thermal_power`       decimal(10,2) DEFAULT 0.00 COMMENT '热功率',
    `in_temperature`      decimal(10,2) DEFAULT 0.00 COMMENT '进水温度',
    `out_temperature`     decimal(10,2) DEFAULT 0.00 COMMENT '回水温度',
    `voltage`             decimal(10,2) DEFAULT 0.00 COMMENT '电压',
    `signal_strength`     int           DEFAULT NULL COMMENT '信号强度',
    `cell_status`         varchar(20)   DEFAULT NULL COMMENT '电池状态',
    `is_opened`           int           DEFAULT 0 COMMENT '是否开户 0否1是',
    `opened_time`         datetime      DEFAULT NULL COMMENT '开户时间',
    `is_expense`          int           DEFAULT 0 COMMENT '是否产生费用 0否1是',
    `is_notify`           int           DEFAULT 0 COMMENT '是否通知 0否1是',
    `is_changed`          int           DEFAULT 0 COMMENT '是否换表 0否1是',
    `is_stop`             int           DEFAULT 0 COMMENT '是否停用 0否1是',
    `house_id`            varchar(32)   DEFAULT NULL COMMENT '房屋ID',
    `company_id`          varchar(32)   DEFAULT NULL COMMENT '公司ID',
    `org_id`              varchar(32)   DEFAULT NULL COMMENT '小区ID',
    `imei_num`            varchar(50)   DEFAULT NULL COMMENT 'IMEI号',
    `dtu_num`             varchar(50)   DEFAULT NULL COMMENT 'DTU号',
    `dtu_type`            int           DEFAULT NULL COMMENT 'DTU类型',
    `dtu_num_status`      varchar(20)   DEFAULT NULL COMMENT 'DTU号状态',
    `chan_num`            varchar(20)   DEFAULT NULL COMMENT '通道号',
    `dtu_status`          varchar(20)   DEFAULT NULL COMMENT 'DTU状态',
    `install_type`        varchar(50)   DEFAULT NULL COMMENT '安装方式',
    `create_dept`         bigint        DEFAULT NULL COMMENT '创建部门',
    `create_by`           varchar(40)   DEFAULT NULL COMMENT '创建者',
    `create_time`         datetime      DEFAULT NULL COMMENT '创建时间',
    `update_by`           varchar(40)   DEFAULT NULL COMMENT '修改者',
    `update_time`         datetime      DEFAULT NULL COMMENT '修改时间',
    `remark`              varchar(500)  DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_company_id` (`company_id`),
    KEY `idx_org_id` (`org_id`),
    KEY `idx_house_id` (`house_id`),
    KEY `idx_meter_num` (`meter_num`),
    KEY `idx_archive_id` (`archive_id`),
    KEY `idx_company_org` (`company_id`, `org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='房屋热量表配表';

-- ========================================
-- 5. pr_heat_command_unit_valve_archive (单元控制阀门配表)
-- 41 persisted columns (unit_id instead of house_id)
-- ========================================
DROP TABLE IF EXISTS `pr_heat_command_unit_valve_archive`;
CREATE TABLE `pr_heat_command_unit_valve_archive` (
    `id`                  varchar(36)   NOT NULL COMMENT '主键',
    `archive_id`          varchar(32)   DEFAULT NULL COMMENT '配表ID(关联)',
    `meter_num`           varchar(32)   DEFAULT NULL COMMENT '表号',
    `card_num`            varchar(32)   DEFAULT NULL COMMENT '卡号',
    `meter_arc_code`      varchar(32)   DEFAULT NULL COMMENT '仪表档案编码',
    `meter_arc_name`      varchar(64)   DEFAULT NULL COMMENT '仪表档案名称',
    `concentrator_code`   varchar(32)   DEFAULT NULL COMMENT '集中器编码',
    `imei_num`            varchar(50)   DEFAULT NULL COMMENT 'IMEI号',
    `product_id`          varchar(32)   DEFAULT NULL COMMENT '产品ID',
    `device_id`           varchar(32)   DEFAULT NULL COMMENT '设备ID',
    `meter_serial`        int           DEFAULT NULL COMMENT '仪表序号',
    `unit_id`             varchar(32)   DEFAULT NULL COMMENT '单元ID',
    `org_id`              varchar(32)   DEFAULT NULL COMMENT '小区ID',
    `company_id`          varchar(32)   DEFAULT NULL COMMENT '公司ID',
    `valve_status`        varchar(10)   DEFAULT NULL COMMENT '阀门状态',
    `setting_status`      int           DEFAULT NULL COMMENT '设定状态',
    `actual_status`       int           DEFAULT NULL COMMENT '实际状态',
    `in_temperature`      decimal(10,2) DEFAULT NULL COMMENT '进水温度',
    `out_temperature`     decimal(10,2) DEFAULT NULL COMMENT '回水温度',
    `voltage`             varchar(20)   DEFAULT NULL COMMENT '电压',
    `valve_time`          datetime      DEFAULT NULL COMMENT '阀门时间',
    `signal_strength`     int           DEFAULT NULL COMMENT '信号强度',
    `reporting_interval`  int           DEFAULT NULL COMMENT '上报间隔',
    `total_degree`        int           DEFAULT NULL COMMENT '总度数',
    `residue_degree`      int           DEFAULT NULL COMMENT '剩余度数',
    `interval_unit`       varchar(20)   DEFAULT NULL COMMENT '间隔单位',
    `valid_time`          int           DEFAULT NULL COMMENT '有效时间',
    `is_changed`          int           DEFAULT 0 COMMENT '是否换表 0否1是',
    `is_stop`             int           DEFAULT 0 COMMENT '是否停用 0否1是',
    `dtu_num`             varchar(50)   DEFAULT NULL COMMENT 'DTU号',
    `dtu_type`            int           DEFAULT NULL COMMENT 'DTU类型',
    `dtu_num_status`      varchar(20)   DEFAULT NULL COMMENT 'DTU号状态',
    `chan_num`            varchar(20)   DEFAULT NULL COMMENT '通道号',
    `install_site`        varchar(128)  DEFAULT NULL COMMENT '安装位置',
    `dtu_status`          varchar(20)   DEFAULT NULL COMMENT 'DTU状态',
    `caliber`             varchar(20)   DEFAULT NULL COMMENT '口径',
    `create_dept`         bigint        DEFAULT NULL COMMENT '创建部门',
    `create_by`           varchar(40)   DEFAULT NULL COMMENT '创建者',
    `create_time`         datetime      DEFAULT NULL COMMENT '创建时间',
    `update_by`           varchar(40)   DEFAULT NULL COMMENT '修改者',
    `update_time`         datetime      DEFAULT NULL COMMENT '修改时间',
    `remark`              varchar(500)  DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_company_id` (`company_id`),
    KEY `idx_org_id` (`org_id`),
    KEY `idx_unit_id` (`unit_id`),
    KEY `idx_meter_num` (`meter_num`),
    KEY `idx_archive_id` (`archive_id`),
    KEY `idx_company_org` (`company_id`, `org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='单元控制阀门配表';

-- ========================================
-- 6. pr_heat_dtu_archive (DTU采集器配表)
-- 17 persisted columns
-- ========================================
DROP TABLE IF EXISTS `pr_heat_dtu_archive`;
CREATE TABLE `pr_heat_dtu_archive` (
    `id`                varchar(36)   NOT NULL COMMENT '主键',
    `dtu_num`           varchar(50)   DEFAULT NULL COMMENT 'DTU号',
    `install_site`      varchar(100)  DEFAULT NULL COMMENT '安装位置',
    `status`            varchar(20)   DEFAULT NULL COMMENT '状态',
    `ip`                varchar(50)   DEFAULT NULL COMMENT 'IP地址',
    `chan_num`          varchar(20)   DEFAULT NULL COMMENT '通道号',
    `channel_num`       int           DEFAULT NULL COMMENT '通道数量',
    `channel_num_time`  datetime      DEFAULT NULL COMMENT '通道数量更新时间',
    `latest_time`       datetime      DEFAULT NULL COMMENT '最新数据时间',
    `last_time`         datetime      DEFAULT NULL COMMENT '最后在线时间',
    `org_id`            varchar(32)   DEFAULT NULL COMMENT '小区ID',
    `company_id`        varchar(32)   DEFAULT NULL COMMENT '公司ID',
    `create_dept`       bigint        DEFAULT NULL COMMENT '创建部门',
    `create_by`         varchar(40)   DEFAULT NULL COMMENT '创建者',
    `create_time`       datetime      DEFAULT NULL COMMENT '创建时间',
    `update_by`         varchar(40)   DEFAULT NULL COMMENT '修改者',
    `update_time`       datetime      DEFAULT NULL COMMENT '修改时间',
    `remark`            varchar(500)  DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_company_id` (`company_id`),
    KEY `idx_org_id` (`org_id`),
    KEY `idx_dtu_num` (`dtu_num`),
    KEY `idx_company_org` (`company_id`, `org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='DTU采集器配表';

-- ========================================
-- 7. pr_heat_unit_hot_archive (单元热表配表)
-- Same as pr_heat_hot_archive but unit_id replaces house_id
-- 61 persisted columns
-- ========================================
DROP TABLE IF EXISTS `pr_heat_unit_hot_archive`;
CREATE TABLE `pr_heat_unit_hot_archive` (
    `id`                  varchar(36)   NOT NULL COMMENT '主键',
    `archive_id`          varchar(32)   DEFAULT NULL COMMENT '配表ID(关联)',
    `meter_arc_code`      varchar(32)   DEFAULT NULL COMMENT '仪表档案编码',
    `meter_arc_name`      varchar(64)   DEFAULT NULL COMMENT '仪表档案名称',
    `meter_num`           varchar(32)   DEFAULT NULL COMMENT '表号',
    `card_num`            varchar(32)   DEFAULT NULL COMMENT '卡号',
    `product_id`          varchar(32)   DEFAULT NULL COMMENT '产品ID',
    `device_id`           varchar(32)   DEFAULT NULL COMMENT '设备ID',
    `meter_serial`        int           DEFAULT NULL COMMENT '仪表序号',
    `concentrator_code`   varchar(32)   DEFAULT NULL COMMENT '集中器编码',
    `hoard_limit`         decimal(10,2) DEFAULT NULL COMMENT '囤积限值',
    `alarm_value`         decimal(10,2) DEFAULT NULL COMMENT '报警值',
    `close_value`         bigint        DEFAULT NULL COMMENT '关阀值',
    `measurement`         varchar(32)   DEFAULT NULL COMMENT '计量方式',
    `install_site`        varchar(128)  DEFAULT NULL COMMENT '安装位置',
    `standard_id`         varchar(32)   DEFAULT NULL COMMENT '收费标准ID',
    `standard_price`      decimal(10,2) DEFAULT 0.00 COMMENT '标准单价',
    `is_steps`            int           DEFAULT 0 COMMENT '是否阶梯 0否1是',
    `start_reading`       decimal(10,2) DEFAULT NULL COMMENT '起始读数',
    `current_reading`     decimal(10,2) DEFAULT 0.00 COMMENT '当前读数',
    `total_used`          decimal(10,2) DEFAULT 0.00 COMMENT '累计用量',
    `trade_times`         int           DEFAULT 0 COMMENT '购买倍数',
    `his_money`           decimal(10,2) DEFAULT 0.00 COMMENT '历史金额',
    `total_money`         decimal(10,2) DEFAULT 0.00 COMMENT '累计金额',
    `total_recharge`      decimal(10,2) DEFAULT 0.00 COMMENT '累计充值',
    `current_balance`     decimal(10,2) DEFAULT 0.00 COMMENT '当前余额',
    `pay_degrees`         decimal(10,2) DEFAULT 0.00 COMMENT '已购量',
    `valve_status`        varchar(10)   DEFAULT NULL COMMENT '阀门状态',
    `total_flow`          decimal(10,2) DEFAULT 0.00 COMMENT '累计流量',
    `cur_flow`            decimal(10,2) DEFAULT 0.00 COMMENT '当前流量',
    `total_worktime`      decimal(10,2) DEFAULT 0.00 COMMENT '累计工作时间',
    `valve_time`          datetime      DEFAULT NULL COMMENT '阀门时间',
    `status1`             varchar(50)   DEFAULT NULL COMMENT '状态1',
    `status2`             varchar(50)   DEFAULT NULL COMMENT '状态2',
    `thermal_power`       decimal(10,2) DEFAULT 0.00 COMMENT '热功率',
    `in_temperature`      decimal(10,2) DEFAULT 0.00 COMMENT '进水温度',
    `out_temperature`     decimal(10,2) DEFAULT 0.00 COMMENT '回水温度',
    `voltage`             decimal(10,2) DEFAULT 0.00 COMMENT '电压',
    `signal_strength`     int           DEFAULT NULL COMMENT '信号强度',
    `cell_status`         varchar(20)   DEFAULT NULL COMMENT '电池状态',
    `is_opened`           int           DEFAULT 0 COMMENT '是否开户 0否1是',
    `opened_time`         datetime      DEFAULT NULL COMMENT '开户时间',
    `is_expense`          int           DEFAULT 0 COMMENT '是否产生费用 0否1是',
    `is_notify`           int           DEFAULT 0 COMMENT '是否通知 0否1是',
    `is_changed`          int           DEFAULT 0 COMMENT '是否换表 0否1是',
    `is_stop`             int           DEFAULT 0 COMMENT '是否停用 0否1是',
    `unit_id`             varchar(32)   DEFAULT NULL COMMENT '单元ID',
    `company_id`          varchar(32)   DEFAULT NULL COMMENT '公司ID',
    `org_id`              varchar(32)   DEFAULT NULL COMMENT '小区ID',
    `imei_num`            varchar(50)   DEFAULT NULL COMMENT 'IMEI号',
    `dtu_num`             varchar(50)   DEFAULT NULL COMMENT 'DTU号',
    `dtu_type`            int           DEFAULT NULL COMMENT 'DTU类型',
    `dtu_num_status`      varchar(20)   DEFAULT NULL COMMENT 'DTU号状态',
    `chan_num`            varchar(20)   DEFAULT NULL COMMENT '通道号',
    `dtu_status`          varchar(20)   DEFAULT NULL COMMENT 'DTU状态',
    `install_type`        varchar(50)   DEFAULT NULL COMMENT '安装方式',
    `create_dept`         bigint        DEFAULT NULL COMMENT '创建部门',
    `create_by`           varchar(40)   DEFAULT NULL COMMENT '创建者',
    `create_time`         datetime      DEFAULT NULL COMMENT '创建时间',
    `update_by`           varchar(40)   DEFAULT NULL COMMENT '修改者',
    `update_time`         datetime      DEFAULT NULL COMMENT '修改时间',
    `remark`              varchar(500)  DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_company_id` (`company_id`),
    KEY `idx_org_id` (`org_id`),
    KEY `idx_unit_id` (`unit_id`),
    KEY `idx_meter_num` (`meter_num`),
    KEY `idx_archive_id` (`archive_id`),
    KEY `idx_company_org` (`company_id`, `org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='单元热表配表';

-- ========================================
-- 8. pr_heat_unit_valve_archive (单元阀门配表)
-- Same structure as pr_heat_command_unit_valve_archive (41 fields)
-- ========================================
DROP TABLE IF EXISTS `pr_heat_unit_valve_archive`;
CREATE TABLE `pr_heat_unit_valve_archive` (
    `id`                  varchar(36)   NOT NULL COMMENT '主键',
    `archive_id`          varchar(32)   DEFAULT NULL COMMENT '配表ID(关联)',
    `meter_num`           varchar(32)   DEFAULT NULL COMMENT '表号',
    `card_num`            varchar(32)   DEFAULT NULL COMMENT '卡号',
    `meter_arc_code`      varchar(32)   DEFAULT NULL COMMENT '仪表档案编码',
    `meter_arc_name`      varchar(64)   DEFAULT NULL COMMENT '仪表档案名称',
    `concentrator_code`   varchar(32)   DEFAULT NULL COMMENT '集中器编码',
    `imei_num`            varchar(50)   DEFAULT NULL COMMENT 'IMEI号',
    `product_id`          varchar(32)   DEFAULT NULL COMMENT '产品ID',
    `device_id`           varchar(32)   DEFAULT NULL COMMENT '设备ID',
    `meter_serial`        int           DEFAULT NULL COMMENT '仪表序号',
    `unit_id`             varchar(32)   DEFAULT NULL COMMENT '单元ID',
    `org_id`              varchar(32)   DEFAULT NULL COMMENT '小区ID',
    `company_id`          varchar(32)   DEFAULT NULL COMMENT '公司ID',
    `valve_status`        varchar(10)   DEFAULT NULL COMMENT '阀门状态',
    `setting_status`      int           DEFAULT NULL COMMENT '设定状态',
    `actual_status`       int           DEFAULT NULL COMMENT '实际状态',
    `in_temperature`      decimal(10,2) DEFAULT NULL COMMENT '进水温度',
    `out_temperature`     decimal(10,2) DEFAULT NULL COMMENT '回水温度',
    `voltage`             varchar(20)   DEFAULT NULL COMMENT '电压',
    `valve_time`          datetime      DEFAULT NULL COMMENT '阀门时间',
    `signal_strength`     int           DEFAULT NULL COMMENT '信号强度',
    `reporting_interval`  int           DEFAULT NULL COMMENT '上报间隔',
    `total_degree`        int           DEFAULT NULL COMMENT '总度数',
    `residue_degree`      int           DEFAULT NULL COMMENT '剩余度数',
    `interval_unit`       varchar(20)   DEFAULT NULL COMMENT '间隔单位',
    `valid_time`          int           DEFAULT NULL COMMENT '有效时间',
    `is_changed`          int           DEFAULT 0 COMMENT '是否换表 0否1是',
    `is_stop`             int           DEFAULT 0 COMMENT '是否停用 0否1是',
    `dtu_num`             varchar(50)   DEFAULT NULL COMMENT 'DTU号',
    `dtu_type`            int           DEFAULT NULL COMMENT 'DTU类型',
    `dtu_num_status`      varchar(20)   DEFAULT NULL COMMENT 'DTU号状态',
    `chan_num`            varchar(20)   DEFAULT NULL COMMENT '通道号',
    `install_site`        varchar(128)  DEFAULT NULL COMMENT '安装位置',
    `dtu_status`          varchar(20)   DEFAULT NULL COMMENT 'DTU状态',
    `caliber`             varchar(20)   DEFAULT NULL COMMENT '口径',
    `create_dept`         bigint        DEFAULT NULL COMMENT '创建部门',
    `create_by`           varchar(40)   DEFAULT NULL COMMENT '创建者',
    `create_time`         datetime      DEFAULT NULL COMMENT '创建时间',
    `update_by`           varchar(40)   DEFAULT NULL COMMENT '修改者',
    `update_time`         datetime      DEFAULT NULL COMMENT '修改时间',
    `remark`              varchar(500)  DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_company_id` (`company_id`),
    KEY `idx_org_id` (`org_id`),
    KEY `idx_unit_id` (`unit_id`),
    KEY `idx_meter_num` (`meter_num`),
    KEY `idx_archive_id` (`archive_id`),
    KEY `idx_company_org` (`company_id`, `org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='单元阀门配表';

-- ========================================
-- 9. pr_heat_temp_archive (温采器配表)
-- 36 persisted columns
-- ========================================
DROP TABLE IF EXISTS `pr_heat_temp_archive`;
CREATE TABLE `pr_heat_temp_archive` (
    `id`                  varchar(36)   NOT NULL COMMENT '主键',
    `archive_id`          varchar(32)   DEFAULT NULL COMMENT '配表ID(关联)',
    `meter_arc_code`      varchar(32)   DEFAULT NULL COMMENT '仪表档案编码',
    `meter_arc_name`      varchar(64)   DEFAULT NULL COMMENT '仪表档案名称',
    `meter_num`           varchar(32)   DEFAULT NULL COMMENT '表号',
    `card_num`            varchar(32)   DEFAULT NULL COMMENT '卡号',
    `valve_status`        varchar(10)   DEFAULT NULL COMMENT '阀门状态',
    `temper`              decimal(10,2) DEFAULT NULL COMMENT '温度',
    `humidity`            decimal(10,2) DEFAULT NULL COMMENT '湿度',
    `voltage`             decimal(10,2) DEFAULT NULL COMMENT '电压',
    `signal_strength`     decimal(10,2) DEFAULT NULL COMMENT '信号强度',
    `collect_time`        datetime      DEFAULT NULL COMMENT '采集时间',
    `reporting_interval`  int           DEFAULT NULL COMMENT '上报间隔',
    `interval_unit`       int           DEFAULT NULL COMMENT '间隔单位',
    `valid_time`          int           DEFAULT NULL COMMENT '有效时间',
    `collect_interval`    int           DEFAULT NULL COMMENT '采集间隔',
    `collect_unit`        int           DEFAULT NULL COMMENT '采集单位',
    `collect_num`         int           DEFAULT NULL COMMENT '采集次数',
    `mov_place`           varchar(20)   DEFAULT NULL COMMENT '移动位置',
    `report_number`       int           DEFAULT NULL COMMENT '上报总数',
    `report_succ_num`     int           DEFAULT NULL COMMENT '上报成功数',
    `report_time`         datetime      DEFAULT NULL COMMENT '上报时间',
    `is_changed`          int           DEFAULT 0 COMMENT '是否换表 0否1是',
    `is_stop`             int           DEFAULT 0 COMMENT '是否停用 0否1是',
    `house_id`            varchar(32)   DEFAULT NULL COMMENT '房屋ID',
    `org_id`              varchar(32)   DEFAULT NULL COMMENT '小区ID',
    `company_id`          varchar(32)   DEFAULT NULL COMMENT '公司ID',
    `concentrator_code`   varchar(32)   DEFAULT NULL COMMENT '集中器编码',
    `imei_num`            varchar(50)   DEFAULT NULL COMMENT 'IMEI号',
    `product_id`          varchar(32)   DEFAULT NULL COMMENT '产品ID',
    `device_id`           varchar(32)   DEFAULT NULL COMMENT '设备ID',
    `create_dept`         bigint        DEFAULT NULL COMMENT '创建部门',
    `create_by`           varchar(40)   DEFAULT NULL COMMENT '创建者',
    `create_time`         datetime      DEFAULT NULL COMMENT '创建时间',
    `update_by`           varchar(40)   DEFAULT NULL COMMENT '修改者',
    `update_time`         datetime      DEFAULT NULL COMMENT '修改时间',
    `remark`              varchar(500)  DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_company_id` (`company_id`),
    KEY `idx_org_id` (`org_id`),
    KEY `idx_house_id` (`house_id`),
    KEY `idx_meter_num` (`meter_num`),
    KEY `idx_archive_id` (`archive_id`),
    KEY `idx_company_org` (`company_id`, `org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='温采器配表';
